GET http://localhost:3000/books
###

POST http://localhost:3000/books
Content-Type: application/json

{
    "id":"9",
    "title":"The gohdfather",
    "author":"Mario Puzao"
}
###

DELETE http://localhost:3000/books/9